name: church_chords
description: "Church Chords App for Choir"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.2.8

flutter:
  uses-material-design: true
  
