name: church_chords
description: "Church Chords App for Choir"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter_test
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
